#!/usr/bin/perl
# Copyright (c) 2010-12, Mitchell Cooper

use warnings;
use strict;
use feature qw|switch say|;

local ($0,     $SIG{TERM},        $SIG{KILL},        $SIG{PIPE}        ) =
      ('juno', \&ircd::terminate, \&ircd::terminate, \&ircd::signalpipe);
local ($SIG{HUP},         $SIG{__WARN__}                               ) =
      (\&ircd::signalhup, \&ircd::WARNING                              );

our ($run_dir, $loop);

BEGIN {
    # find the directory to run from
    if ( not defined ($run_dir = shift @ARGV) ) {
        die "No directory specified.\n"
    }

    # make sure the run directory exists.
    if (!-d $run_dir) {
        die "Run directory does not exist.\n"
    }

    chdir $run_dir or die "Can't access run directory.\n";
    unshift @INC, "$run_dir/inc";

    require ircd;
    ircd::begin()
}

ircd::boot();
ircd::loop();
